---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: talos-metallb
  namespace: flux-system
spec:
  interval: 12h0m0s
  ref:
    branch: main
  url: https://github.com/thejimnicholson/talos-metallb.git
