---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homepage
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://git.thejimnicholson.com/homelab/homepage.git
 