---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dns-clusterissuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: thejimnicholson@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - selector:
        dnsZones:
          - "thejimnicholson.com"
      dns01:
        route53:
          region: us-west-2
          accessKeyIDSecretRef:
            name: aws-route53-creds
            key: AWS_ACCESS_KEY
          secretAccessKeySecretRef:
            name: aws-route53-creds
            key: AWS_SECRET_KEY