---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nfs-external-subdir-provisioner
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: nfs-subdir-external-provisioner
  targetNamespace: nfs-provisioner
  values:
    nfs:
      path: /mnt/data/k8s/talos
      server: 10.0.96.14
