---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./
  prune: false
  sourceRef:
    kind: GitRepository
    name: keycloak
