---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: jenkins
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: master
  url: https://github.com/thejimnicholson/jenkins.git
