---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: wiki-js
  namespace: flux-system
spec:
  chart:
    spec:
      chart: wiki
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: requarks
  install:
    createNamespace: true
  interval: 10m0s
  releaseName: wiki-js
  targetNamespace: wiki
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: dns-clusterissuer
      hosts:
        - host: wiki.thejimnicholson.com
          paths: 
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - wiki.thejimnicholson.com
          secretName: wiki-thejimnicholson-com
    postgresql:
      enabled: false
      postgresqlDatabase: wiki-db
      postgresqlHost: wiki-db-rw
      postgresqlUser: wiki-db
      existingSecret: wiki-db-app
      existingSecretKey: password
