apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wiki-db
  namespace: wiki
spec:
  instances: 3
  bootstrap:
    initdb:
      database: wiki-db
  storage:
    storageClass: nfs-client
    size: 5Gi
