---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cloudnative-pg
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cnpg
  install:
    createNamespace: true
  interval: 10m0s
  releaseName: cnpg
  targetNamespace: cnpg-system
