---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: secret-generator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kubernetes-secret-generator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mittdewald
  install:
    createNamespace: true
  interval: 10m0s
  releaseName: secret-generator
  targetNamespace: secret-generator
